# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgisFORM
                                 A QGIS plugin
 This is a plugin for landslide susceptibility assessments using the First Order Reliability Method (FORM)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-14
        copyright            : (C) 2024 by Bin Tong (HHU)
        email                : bin_tong12@hhu.edu.cn
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QgisFORM class from file QgisFORM.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .QGIS_FORM import QgisFORM
    return QgisFORM(iface)
